### ISSUE TITLE
Backporting missing PRs from the original project

### ISSUE THREAD

**Issue by dotvladaz** [MaceWindu/sourcemap-tools#16]
Hello,
I'm considering moving Office Web apps from the original tool library to this one to leverage the .NET Core support. 
This project is missing the last two PRs from the original one, which are critical to us:

[use OriginalName for deminification](https://github.com/microsoft/sourcemap-toolkit/pull/86)
and
[Move function names by 1](https://github.com/microsoft/sourcemap-toolkit/pull/88)

Any objections?

We also need the StackFrame.MethodName and the StackFrame.FilePath to have public setters. If the deminifier fails to retrieve those, we're want to assign the original minified values before serializing and reporting. 
Another way would be to add a flag to DeminifyStackTrace() function to support this behavior in the library. 

Thoughts?

Thanks

**Comment by MaceWindu** [comment]
I've seen those PRs and decided to not merge them as they actually doesn't add any value. But I will review it once more, maybe I missed the point

**Comment by MaceWindu** [comment]
Also one of issues of those PRs - they don't introduce tests to demonstrate actual issue and how it was fixed

**Comment by MaceWindu** [comment]
I've released new preview with requested changes. Will wait for feedback and release final version somewhere next week

**Comment by dotvladaz** [comment]
Thanks! I'm not sure [https://github.com/microsoft/sourcemap-toolkit/pull/88](https://github.com/microsoft/sourcemap-toolkit/pull/88) was migrated. It should have added "fixOffByOneEnabled" argument and more logic in the StackTraceDeminifier.DeminifyStackTrace() function.
Also, have you made the arguments mandatory intentionally? I'm fine with that, but it can break some usages. 
Thanks again!

**Comment by MaceWindu** [comment]
>I'm not sure https://github.com/microsoft/sourcemap-toolkit/pull/88 was migrated. It should have added "fixOffByOneEnabled" argument and more logic in the StackTraceDeminifier.DeminifyStackTrace() function.

I've [added logic](https://github.com/MaceWindu/sourcemap-tools/blob/master/src/SourceMapTools/CallstackDeminifier/StackTraceDeminifier.cs#L50-L64) (refactored it a bit). But decided to not introduce extra parameter as I don't see how it will be useful with `fixOffByOneEnabled=false`. If you think it is needed - I can add it

> have you made the arguments mandatory intentionally

not a big fan of default parameters and I release major version, so small changes like that are fine

**Comment by dotvladaz** [comment]
Thanks for the clarification. 
I'm perfectly fine with the non-default param.
Seems like in our code all the scenarios that are setting preferSourceMapsSymbols, are also enabling fixOffByOneEnabled, so we should be fine. 
Since I'm not an expert, I've asked Alex, the engineer who's made the original change to review it.

**Comment by MaceWindu** [comment]
@dotvladaz any additional change requests or I can release 2.0.0 as is?
